exports.Method = {
	0: "None",
	1: "Oodle",
	2: "Brotli",
};

exports.EUsmapPropertyType = {
	0: "ByteProperty",
	1: "BoolProperty",
	2: "IntProperty",
	3: "FloatProperty",
	4: "ObjectProperty",
	5: "NameProperty",
	6: "DelegateProperty",
	7: "DoubleProperty",
	8: "ArrayProperty",
	9: "StructProperty",
	10: "StrProperty",
	11: "TextProperty",
	12: "InterfaceProperty",
	13: "MulticastDelegateProperty",
	14: "WeakObjectProperty",
	15: "LazyObjectProperty",
	16: "AssetObjectProperty",
	17: "SoftObjectProperty",
	18: "UInt64Property",
	19: "UInt32Property",
	20: "UInt16Property",
	21: "Int64Property",
	22: "Int16Property",
	23: "Int8Property",
	24: "MapProperty",
	25: "SetProperty",
	26: "EnumProperty",
	27: "FieldPathProperty",

	255: "Unknown",
};